# If you do not have OpenSSL installed, change
# the following line to use 'http://'
source 'https://rubygems.org'

# For faster file watcher updates on Windows:
gem 'wdm', '~> 0.1.0', platforms: [:mswin, :mingw]

# Windows does not come with time zone data
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]

# Middleman Gems
gem 'middleman', '~> 4.2'

# Live reload
gem 'middleman-livereload', '~> 3.4.3'

# Minify html
gem 'middleman-minify-html', '~> 3.4.1'

# pandoc
gem 'pandoc-ruby'

# imageoptim
#gem "middleman-imageoptim", :git => "https://github.com/plasticine/middleman-imageoptim", :branch => "master"
gem "middleman-critical", "~>0.0.2"

gem "middleman-typogruby", :git => "https://github.com/ssbx/middleman-typogruby", :branch => "master"

gem "handlebars", "~>0.7.0"
